#ifndef SCHEMA_VERIFIER_H
#define SCHEMA_VERIFIER_H

/* Generated by flatcc 0.6.0-pre FlatBuffers schema compiler for C by dvide.com */

#ifndef SCHEMA_READER_H
#include "schema_reader.h"
#endif
#include "flatcc/flatcc_verifier.h"
#include "flatcc/flatcc_prologue.h"

static int MnistProt_Stats_verify_table(flatcc_table_verifier_descriptor_t *td);
static int MnistProt_InferenceInput_verify_table(flatcc_table_verifier_descriptor_t *td);
static int MnistProt_InferenceOutput_verify_table(flatcc_table_verifier_descriptor_t *td);
static int MnistProt_Commands_verify_table(flatcc_table_verifier_descriptor_t *td);

static int MnistProt_Stats_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_field(td, 0, 1, 1) /* version */)) return ret;
    if ((ret = flatcc_verify_field(td, 1, 4, 4) /* freq */)) return ret;
    if ((ret = flatcc_verify_field(td, 2, 1, 1) /* mode */)) return ret;
    return flatcc_verify_ok;
}

static inline int MnistProt_Stats_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, MnistProt_Stats_identifier, &MnistProt_Stats_verify_table);
}

static inline int MnistProt_Stats_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, MnistProt_Stats_type_identifier, &MnistProt_Stats_verify_table);
}

static inline int MnistProt_Stats_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &MnistProt_Stats_verify_table);
}

static inline int MnistProt_Stats_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &MnistProt_Stats_verify_table);
}

static int MnistProt_InferenceInput_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_vector_field(td, 0, 0, 4, 4, INT64_C(1073741823)) /* digit */)) return ret;
    return flatcc_verify_ok;
}

static inline int MnistProt_InferenceInput_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, MnistProt_InferenceInput_identifier, &MnistProt_InferenceInput_verify_table);
}

static inline int MnistProt_InferenceInput_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, MnistProt_InferenceInput_type_identifier, &MnistProt_InferenceInput_verify_table);
}

static inline int MnistProt_InferenceInput_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &MnistProt_InferenceInput_verify_table);
}

static inline int MnistProt_InferenceInput_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &MnistProt_InferenceInput_verify_table);
}

static int MnistProt_InferenceOutput_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_vector_field(td, 0, 0, 4, 4, INT64_C(1073741823)) /* output_f */)) return ret;
    if ((ret = flatcc_verify_field(td, 1, 1, 1) /* output_n */)) return ret;
    if ((ret = flatcc_verify_field(td, 2, 4, 4) /* timer_ms */)) return ret;
    return flatcc_verify_ok;
}

static inline int MnistProt_InferenceOutput_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, MnistProt_InferenceOutput_identifier, &MnistProt_InferenceOutput_verify_table);
}

static inline int MnistProt_InferenceOutput_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, MnistProt_InferenceOutput_type_identifier, &MnistProt_InferenceOutput_verify_table);
}

static inline int MnistProt_InferenceOutput_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &MnistProt_InferenceOutput_verify_table);
}

static inline int MnistProt_InferenceOutput_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &MnistProt_InferenceOutput_verify_table);
}

static int MnistProt_Commands_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_field(td, 0, 1, 1) /* cmd */)) return ret;
    if ((ret = flatcc_verify_table_field(td, 1, 0, &MnistProt_Stats_verify_table) /* stats */)) return ret;
    if ((ret = flatcc_verify_table_field(td, 2, 0, &MnistProt_InferenceInput_verify_table) /* input */)) return ret;
    if ((ret = flatcc_verify_table_field(td, 3, 0, &MnistProt_InferenceOutput_verify_table) /* ouput */)) return ret;
    return flatcc_verify_ok;
}

static inline int MnistProt_Commands_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, MnistProt_Commands_identifier, &MnistProt_Commands_verify_table);
}

static inline int MnistProt_Commands_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, MnistProt_Commands_type_identifier, &MnistProt_Commands_verify_table);
}

static inline int MnistProt_Commands_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &MnistProt_Commands_verify_table);
}

static inline int MnistProt_Commands_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &MnistProt_Commands_verify_table);
}

#include "flatcc/flatcc_epilogue.h"
#endif /* SCHEMA_VERIFIER_H */
